#home:
#  path: /
#  defaults: { _controller: 'AppBundle\Controller\DefaultController::indexAction' }
#  methods:  GET
#

setupcheck:
    path: /api/setup-check
    controller: App\Controller\DefaultController::setupCheck

exchangerates:
    path: /api/exchange-rates/{date}
    controller: App\Controller\ExchangeRatesController::index
    methods: GET
    requirements:
        date: '\d{4}-\d{2}-\d{2}'

index:
    path: /{wildcard}
    defaults: {
        _controller: App\Controller\DefaultController::index
    }
    requirements:
        wildcard: .*


