
parameters:

services:
    App\Service\Nbp\ApiClient:
        public: true
        arguments:
            $baseUrl: 'https://api.nbp.pl/api/'
            $httpClient: '@http_client'

    App\Service\Nbp\ExchangeRatesService:
        public: true
        arguments:
            $nbpClient: '@App\Service\Nbp\ApiClient'